"""Contract: ADR-0013 -- honest passthrough with the deny/rewrite/merge table,
owned-section typo warnings, schema key, env-role rejection, provenance header."""

import pytest
import tomli

from comfy_env.config import load_config, parse_config
from comfy_env.packages.toml_generator import build_env_toml, write_env_pixi_toml


def _manifest(config_dict, **kw):
    cfg = parse_config(config_dict)
    kw.setdefault("torch_index", None)
    kw.setdefault("bootstrap_python", "3.12")
    kw.setdefault("log", lambda m: None)
    return build_env_toml("t-env", cfg, **kw)


def test_unknown_tables_are_forwarded_to_the_feature():
    m = _manifest({"tasks": {"test": "pytest"},
                   "some-future-pixi-table": {"x": 1}})
    feat = m["feature"]["node"]
    assert feat["tasks"] == {"test": "pytest"}
    assert feat["some-future-pixi-table"] == {"x": 1}


def test_activation_is_merged_and_compiler_wins_on_collision():
    m = _manifest({"activation": {
        "env": {"FOO": "1", "KMP_DUPLICATE_LIB_OK": "FALSE"},
        "scripts": ["setup.sh"],
    }})
    act = m["feature"]["node"]["activation"]
    assert act["env"]["FOO"] == "1"                       # author passes
    assert act["env"]["KMP_DUPLICATE_LIB_OK"] == "TRUE"   # compiler wins
    assert act["scripts"] == ["setup.sh"]                 # author passes


def test_compiler_owned_tables_are_denied():
    with pytest.raises(ValueError, match=r"compiler-owned.*\[environments\]"):
        _manifest({"environments": {"default": {}}})
    with pytest.raises(ValueError, match=r"compiler-owned.*\[feature\]"):
        _manifest({"feature": {"extra": {}}})
    with pytest.raises(ValueError, match="workspace key.*platforms"):
        _manifest({"workspace": {"platforms": ["win-64"]}})


def test_owned_section_typos_warn(capsys):
    parse_config({"cuda": {"pakages": ["cumesh"]}})
    assert "unrecognized key 'pakages' in [cuda]" in capsys.readouterr().err
    parse_config({"settings": {"isolat": True}})
    assert "unrecognized key 'isolat' in [settings]" in capsys.readouterr().err


def test_schema_version_key():
    assert parse_config({"schema": 1}) is not None
    with pytest.raises(ValueError, match="schema = 2 is not supported"):
        parse_config({"schema": 2})


def test_env_file_rejects_root_only_sections(tmp_path):
    p = tmp_path / "comfy-env.toml"
    p.write_text("[settings]\nisolate = true\n", encoding="utf-8")
    with pytest.raises(ValueError, match=r"\[settings\] belong in comfy-env-root.toml"):
        load_config(p)
    p.write_text('[node_reqs]\nX = "https://github.com/x/X"\n', encoding="utf-8")
    with pytest.raises(ValueError, match=r"\[node_reqs\] belong in"):
        load_config(p)


def test_written_manifest_has_provenance_header_and_parses(tmp_path):
    cfg = parse_config({"dependencies": {"ffmpeg": "*"}})
    write_env_pixi_toml(
        env_manifest_dir=tmp_path, env_name="t-env", cfg=cfg,
        torch_index=None, bootstrap_python="3.12", log=lambda m: None)
    raw = (tmp_path / "pixi.toml").read_text(encoding="utf-8")
    assert raw.startswith("# Generated by comfy-env")
    assert "Fix errors there" in raw
    with open(tmp_path / "pixi.toml", "rb") as f:
        data = tomli.load(f)  # header comments must not break TOML parsing
    assert "ffmpeg" in data["feature"]["node"]["dependencies"]
